spring:
  application:
    name: church-secretariat-service

  datasource:
    url: jdbc:postgresql://localhost:5432/church_db
    username: church_user
    password: church_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
    clean-disabled: false